### ISSUE TITLE
想法太棒了，为什么不继续开发了呢？

### ISSUE THREAD

**Issue by coffee222** [EtherDream/decent-cdn#3]
被作者的创意折服，希望能够看到成品。

**Comment by EtherDream** [comment]
还在开发，还有很多新的功能在试验中~

**Comment by wll8** [comment]
支持！这样一个项目，展现了各种方面的实力。

宏观思考、细节思考、对网络安全、算法运用、主流前端技术、当然还有对网络各大服务商了解~

太期待这个项目了！

**Comment by EtherDream** [comment]
项目已移至 https://github.com/EtherDream/freecdn
